name: center_webview
description: A new Flutter package for web. Keeps your contents in the center of the screen and adjusts to the responsive change in size.
version: 0.0.1
homepage: https://github.com/ajith-m-doodlebug/center_webview.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


